sudo: required 
services:
  - docker

script:
  - docker build -t marisabel/node .
  - docker images marisabel/node

before_deploy:
  - docker login -u $dockerUserName -p $dockerPass

deploy:
  provider: script
  script: docker push marisabel/node
  on: 
    branch: master
