sudo: required 
services:
  - docker

script:
  - docker build -t marisabelc/node .
  - docker images marisabelc/node

before_deploy:
  - docker login -u $dockerUserName -p $dockerPass

deploy:
  provider: script
  script: docker push marisabelc/node
  on: 
    branch: master
